linters:
  enable:
    - goconst
    - godot
    - goimports
    - gosec
    - gofmt
    - stylecheck

linter-settings:
  govet:
    enable-all: true

  godot:
    scope: all
    capital: true

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
